### ISSUE TITLE
Server list that have this plugin on readme

### ISSUE THREAD

**Issue by Blueberryy** [Uncle-Tio/nmrih-maps-translation-files#1]
Add list of servers that use this plugin on readme please

**Comment by Uncle-Tio** [comment]
Once I'm done organizing the repository, I'll try to do it.

**Comment by Uncle-Tio** [comment]
I tried to find an automatic way to track the servers using this plugin but I couldn't find it. What I can do is make a "manual list", but it will depend on the server owners say "my server is using"... sorry :/

**Comment by Blueberryy** [comment]
Okay. I hope you will add more translations for custom maps

**Comment by Uncle-Tio** [comment]
I will :)
